### PR TITLE
issue #38 xdebug not working after Dockerfile Change.

### LINKED ISSUE #38: xdebug not working after changes to php-fpm Dockerfile

### LINKED ISSUE #40: Syrup pump calculations added to receipt
1.  In receipt, do not display if set to none.
2. In cart, correct remove call to remove specific pump item.
3. Set a proper key in cart. 
4. Store the pumps with option 3 in the DB. 
5. Recall pumps via explode from db.

### LINKED ISSUE #41: Receipt: syrups with no pumps qty in DB throw exception

### PR DESCRIPTION
**Pull request by bpawletzki**

### CODE REVIEW

File: public/receipt.php [hunk 1]
```diff
@@ -92,8 +92,11 @@ function guidv4($data = null)
 
 
                 //adding price per syrup pump
-                if ($productOption3 != "None") {
-                    $price = $price + ($qty * 0.25);
+                if (!empty($productOption3) && $productOption3 != "None") {
+                    if (empty($productOption3Qty)) {
```
Comment (nramey3) [inline public/receipt.php]: should be productOption3quantity as well

File: public/receipt.php [hunk 2]
```diff
@@ -92,8 +92,11 @@ function guidv4($data = null)
...
+                        $productOption3Qty = 1;
+                    }
+                    $price = $price + ($productOption3Qty * 0.25);
```
Comment (nramey3) [inline public/receipt.php]: same as above

**Review by nramey3 — CHANGES_REQUESTED** [review]
productOption3Qty to be changed to productOption3quantity on lines 96 97 and 99 of receipt

**Review by nramey3 — APPROVED** [review]
